[package]
name = "xeo"
version = "0.1.0"
authors = ["ricky han <github@rickyhan.com>"]

[dependencies]
oping = "0.3.3"

openssl = "0.10.10"

serde = "1.0"
serde_derive = "1.0"
bincode = "1.0.1"

structopt = "0.2"

log = "0.4"
fern = "0.5"
chrono = "0.4"
